CREATE TABLE EMPLOYEE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255),
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID);